obj-y		+= gpio.o
## to compile for host module decomment here
## mknod /dev/gpio0 c 212 0
## mknod /dev/gpio1 c 212 1
## mknod /dev/selectmap0 c 214 0
## chmod a+rwx  /dev/gpio0  /dev/gpio1  /dev/selectmap0
#obj-m		+= gpio.o
#
#grmon-all:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
#
#grmon-clean:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
