vlib modelsim
vlib modelsim/grlib 
vlib modelsim/altera 
vlib modelsim/altera_mf 
vlib modelsim/cycloneiii 
vlib modelsim/dware 
vlib modelsim/synplify 
vlib modelsim/techmap 
vlib modelsim/eth 
vlib modelsim/opencores 
vlib modelsim/gaisler 
vlib modelsim/esa 
vlib modelsim/fmf 
vlib modelsim/spansion 
vlib modelsim/gsi 
vlib modelsim/cypress 
vlib modelsim/hynix 
vlib modelsim/micron 
vlib modelsim/work 
