.TH KDSTAT 8 "Debian GNU/Linux" "DEBIAN"
.SH NAME
kdstat \- program to show and change internal kerneld state
.SH SYNOPSIS
.B kdstat
.br
.B kdstat
.I "[debug|nodebug]"
.br
.B kdstat
.I "[keep|nokeep]"
.br
.B kdstat
.I "flush"
.br
.B kdstat
.I delay=<time>
.SH "DESCRIPTION"
This manual package describes
.BR kdstat
, a program used to debug kerneld. You can use it to view (and change)
the internal state of a running kerneld.
.SH OPTIONS
When run,
.BR kdstat
always displays the current state of kerneld. Given the proper options it can
do much more. All legal options are explained below.
.TP
.B debug, nodebug
Turn kerneld debugging mode on or off. If turned on, kerneld displays
what it is doing on the console.
.TP
.B keep, nokeep
Turn keeping of modules on or off. If turned off (the default), modules
are unloaded when they have not been used for a while. See
.I delay
for more information about the timeout used.
.TP
.B flush
Flush the IPC message queue used to communicate with kerneld
.TP
.B delay=<time>
Change the timeout kerneld waits before removing a module from the kernel.
.SH "SEE ALSO"
\fBmodules\fP(2), \fBkerneld\fP(8).
.SH AUTHOR
This manual page was written by Wichert Akkerman <wakkerma@debian.org>
for the Debian GNU/Linux system.
