/* generated by bootloader.pl */
#define BOOTLOADER_FREQ_KHZ 40000
#define BOOTLOADER_SRAMSZ_KB 0
#define BOOTLOADER_SDRAMSZ_MB 16
#define BOOTLOADER_BAUD 38400
#define CONFIG_KERNEL_COMMAND_LINE "console=tty0 video=grvga:800x480,16,768000"

#define BOOTLOADER_memcfg1  0x28022
#define BOOTLOADER_memcfg2  0x81006020
#define BOOTLOADER_uart     0x83
#define BOOTLOADER_loopback 0x0
#define BOOTLOADER_flow     0x0
#define BOOTLOADER_ftreg    0x13b000

#define BOOTLOADER_grlib_sdram 0x8100013b
#define BOOTLOADER_ddr2spa_cfg1 0xffe08616
#define BOOTLOADER_ddr2spa_cfg3 0x13650000
#define BOOTLOADER_ddrspa_cfg1 0xffe08616

#define BOOTLOADER_freq      40500000

#define BOOTLOADER_ramsize   0xfff000
#define BOOTLOADER_romsize   0x800000
#define BOOTLOADER_stack     0x40ffefe0

#define BOOTLOADER_physbase  0x40000000
