#undef __DBL_MIN_EXP__
#undef __FLT_MIN__
#undef __CHAR_BIT__
#undef __WCHAR_MAX__
#undef __DBL_DENORM_MIN__
#undef __FLT_EVAL_METHOD__
#undef BOOTLOADER_BAUD
#undef __DBL_MIN_10_EXP__
#undef __FINITE_MATH_ONLY__
#undef __GNUC_PATCHLEVEL__
#undef sparc
#undef __SHRT_MAX__
#undef __LDBL_MAX__
#undef __linux
#undef __unix
#undef __LDBL_MAX_EXP__
#undef __linux__
#undef __SCHAR_MAX__
#undef BOOTLOADER_uart
#undef __USER_LABEL_PREFIX__
#undef __STDC_HOSTED__
#undef __LDBL_HAS_INFINITY__
#undef __DBL_DIG__
#undef __FLT_EPSILON__
#undef BOOTLOADER_physbase
#undef __LDBL_MIN__
#undef __unix__
#undef __DECIMAL_DIG__
#undef __gnu_linux__
#undef BOOTLOADER_memcfg1
#undef BOOTLOADER_memcfg2
#undef __LDBL_HAS_QUIET_NAN__
#undef __GNUC__
#undef BOOTLOADER_romsize
#undef BOOTLOADER_FREQ_KHZ
#undef __DBL_MAX__
#undef __DBL_HAS_INFINITY__
#undef BOOTLOADER_stack
#undef __DBL_MAX_EXP__
#undef __LONG_LONG_MAX__
#undef __sparc__
#undef __GXX_ABI_VERSION
#undef __FLT_MIN_EXP__
#undef BOOTLOADER_freq
#undef __DBL_MIN__
#undef BOOTLOADER_ddr2spa_cfg1
#undef BOOTLOADER_ddr2spa_cfg3
#undef __DBL_HAS_QUIET_NAN__
#undef __REGISTER_PREFIX__
#undef __NO_INLINE__
#undef __FLT_MANT_DIG__
#undef __VERSION__
#undef __sparc
#undef __leonbare__
#undef unix
#undef BOOTLOADER_loopback
#undef __SIZE_TYPE__
#undef __ELF__
#undef __FLT_RADIX__
#undef __LDBL_EPSILON__
#undef __FLT_HAS_QUIET_NAN__
#undef __FLT_MAX_10_EXP__
#undef __LONG_MAX__
#undef __FLT_HAS_INFINITY__
#undef BOOTLOADER_SDRAMSZ_MB
#undef BOOTLOADER_grlib_sdram
#undef linux
#undef CONFIG_KERNEL_COMMAND_LINE
#undef __LDBL_MANT_DIG__
#undef __WCHAR_TYPE__
#undef __FLT_DIG__
#undef __INT_MAX__
#undef __FLT_MAX_EXP__
#undef __DBL_MANT_DIG__
#undef __WINT_TYPE__
#undef __LDBL_MIN_EXP__
#undef __LDBL_MAX_10_EXP__
#undef __DBL_EPSILON__
#undef BOOTLOADER_flow
#undef __FLT_DENORM_MIN__
#undef __FLT_MAX__
#undef __FLT_MIN_10_EXP__
#undef __GNUC_MINOR__
#undef __DBL_MAX_10_EXP__
#undef __LDBL_DENORM_MIN__
#undef __PTRDIFF_TYPE__
#undef BOOTLOADER_SRAMSZ_KB
#undef BOOTLOADER_ramsize
#undef BOOTLOADER_ftreg
#undef __LDBL_MIN_10_EXP__
#undef __LDBL_DIG__
#undef __ASSEMBLER__
#undef BOOTLOADER_ddrspa_cfg1
