.\" Copyright (C) 1996 Free Software Foundation, Inc.
.\" This file is distributed according to the GNU General Public License.
.\" See the file COPYING in the top level source directory for details.
.\"
.TH DELETE_MODULE 2 "26 Dec 1996" Linux "Linux Module Support"
.SH NAME
delete_module \- delete a loadable module entry
.SH SYNOPSIS
.nf
.B #include <linux/module.h>
.sp
.BI "int delete_module(const char *" name );
.fi
.SH DESCRIPTION
.B delete_module
attempts to remove an unused loadable module entry.  If \fIname\fP
is \fBNULL\fP, all unused modules marked auto-clean will be removed.
This system call is only open to the superuser.
.SH "RETURN VALUE"
On success, zero is returned.  On error, \-1 is returned and \fIerrno\fP
is set appropriately.
.SH ERRORS
.TP
.B EPERM
The user is not the superuser.
.TP
.B ENOENT
No module by that name exists.
.TP
.B EINVAL
\fIname\fP was the empty string.
.TP
.B EBUSY
The module is in use.
.TP
.B EFAULT
.I name
is outside the program's accessible address space.
.SH "SEE ALSO
.BR create_module "(2), " init_module "(2), " query_module "(2).
