.TH KERNELVERSION 1 "Debian GNU/Linux" "DEBIAN"
.SH NAME
kernelversion \- program to report major version of kernel
.SH SYNOPSIS
.B kernelversion
.SH "DESCRIPTION"
.B kernelversion
is a small program for Debian/GNU Linux to report the major version of
the kernel. This version is used by the modutils package to calculate
the directories for kernel modules. See
.B /etc/modules.conf
for a sample usage.
.SH OPTIONS
.B kernelversion
simply ignores any arguments you give.
.SH AUTHOR
This manual page was written by Wichert Akkerman <wakkerma@debian.org>
for the Debian GNU/Linux system.
